version: "3.9"

services:
  backend:
    build:
      context: ./InvoiceProcessor.API
      dockerfile: Dockerfile
    env_file:
      - ./InvoiceProcessor.API/.env
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "8080:80"
    networks:
      - invoice-net

  web:
    build: ./frontend
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://backend/api
    depends_on:
      - backend
    networks:
      - invoice-net

networks:
  invoice-net:
    driver: bridge
