# fly.toml app configuration file generated for redirect-app-broken-meadow-7238 on 2025-06-19T23:31:37+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'redirect-app-broken-meadow-7238'
primary_region = 'syd'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
